dist: bionic
language: node_js
cache:
    directories:
        - node_modules
addons:
  chrome: stable
node_js:
 - "14"
install: make node_modules
services:
  - xvfb
before_script:
  - make serve_bg
  - export DISPLAY=:99.0
script: make check ARGS=--single-run
